Repository myhealthconnectsociety/project-healthcare, pull requests merged in 2024-08, with the labels that each got.

#4 Feature-geolocation
  .gitignore
  .idx/dev.nix
  .pre-commit-config.yaml
  README.md
  poetry.lock
  pyproject.toml
  xcov19/Makefile
  xcov19/app/controllers/geolocation.py
  xcov19/app/dto.py
  xcov19/app/middleware.py
  xcov19/app/services.py
  xcov19/check.sh
  xcov19/domain/models/provider.py
  xcov19/package-lock.json
  xcov19/package.json
  xcov19/run.sh
  xcov19/tests/conftest.py
  xcov19/tests/test_services.py
Labels: enhancement, help wanted

#5 Feature geolocation
  Makefile
  check.sh
  run.sh
Labels: bug

#25 Checks for correct signature used by the implementation class.
  Makefile
  xcov19/app/services.py
  xcov19/tests/conftest.py
  xcov19/tests/test_services.py
  xcov19/utils/__init__.py
  xcov19/utils/mixins.py
Labels: enhancement

#23 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, C4GT Coding

#42 Feature location impl
  Makefile
  xcov19/app/controllers/diagnose.py
  xcov19/app/controllers/geolocation.py
  xcov19/app/middleware.py
  xcov19/app/services.py
  xcov19/app/settings.py
  xcov19/domain/repository.py
  xcov19/domain/repository_interface.py
  xcov19/dto.py
  xcov19/services/__init__.py
  xcov19/services/geolocation.py
  xcov19/tests/conftest.py
  xcov19/tests/test_services.py
  xcov19/utils/mixins.py
Labels: enhancement
