Repository myhealthconnectsociety/project-healthcare, pull requests merged in 2025-01, with the labels that each got.

#116 Create trivy.yaml
  .github/actions/trivy.yaml
Labels: security vulnerability

#114 Creating Documentation folder in project root.
  README.md
  docs/images/flowchart.jpg
  docs/images/sequence-diagram.jpg
  docs/project_healthcare_documentation.md
Labels: documentation

#135 Docs: Add GraphQL backend roadmap
  docs/images/class-diagram.svg
  docs/images/graph.svg
  docs/images/seq-diagram.svg
  docs/roadmap.md
Labels: documentation, enhancement, good first issue, help wanted
